# Generated by Django 2.1.1 on 2018-09-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopPageContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CopyText', models.CharField(max_length=255)),
                ('MessageText', models.CharField(max_length=255)),
            ],
        ),
    ]
