# Generated by Django 2.1.1 on 2018-09-01 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopPageContents',
            new_name='TopPageContent',
        ),
    ]
