# Generated by Django 2.1.1 on 2018-09-01 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogparagraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogparagraph',
            name='BlogData',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BlogParagraphs', to='blog.BlogData'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='Date',
            field=models.DateField(),
        ),
    ]
