# Generated by Django 2.1.1 on 2018-09-02 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180901_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogparagraph',
            old_name='Paragraph',
            new_name='ParagraphText',
        ),
        migrations.AddField(
            model_name='blogparagraph',
            name='ParagraphImage',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='blogparagraph',
            name='BlogData',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogData'),
        ),
    ]
