# Generated by Django 2.1.1 on 2018-09-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180902_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogparagraph',
            name='ParagraphImage',
            field=models.ImageField(blank=True, null=True, upload_to='img_blog/%Y/%m/%d'),
        ),
    ]
