# Generated by Django 2.1.1 on 2018-09-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageUrl', models.ImageField(upload_to='img_products/%Y/%m/%d')),
                ('ProductData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductData')),
            ],
        ),
    ]
